apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <APP_NAME>
  namespace: <APP_NAME>
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - <APP_NAME>.<BINN_STAGING_DNS>
    secretName: <APP_NAME>-tls
  rules:
  -  host: <APP_NAME>.<BINN_STAGING_DNS>
     http:
      paths:
        backend:
          service:
            name: <APP_NAME>-service
            port:
              number: 3000