name: k8s Pipeline
on:
  workflow_call:
    secrets:
      APP_NAME:
        required: true
jobs:
  setup_nestjs:
    - name: Update deployment file
      run: |
        sed -i 's|<APP_NAME>|${{ env.IMAGE_NAME }}-${{ env.GIT_BRANCH }}|g' $GITHUB_WORKSPACE/ghactions/.github/config/k8s_deployment.yml
